name: generate_links

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run a one-line script
              run: ./generate.sh
            - name: Deploy to gh-pages
              run: ./deploy.sh
